// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using SeniorLearnConsole;

#nullable disable

namespace SeniorLearnConsole.Migrations
{
    [DbContext(typeof(MyAppContext))]
    partial class MyAppContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.7")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("SeniorLearnConsole.Data.Course", b =>
                {
                    b.Property<int>("CourseId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("CourseId"));

                    b.Property<string>("CourseName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("ProMembermemberId")
                        .HasColumnType("int");

                    b.Property<int>("proId")
                        .HasColumnType("int");

                    b.HasKey("CourseId");

                    b.HasIndex("ProMembermemberId");

                    b.ToTable("Courses");
                });

            modelBuilder.Entity("SeniorLearnConsole.Data.Member", b =>
                {
                    b.Property<int>("memberId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("memberId"));

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Member_Type")
                        .IsRequired()
                        .HasMaxLength(13)
                        .HasColumnType("nvarchar(13)");

                    b.HasKey("memberId");

                    b.ToTable("Members");

                    b.HasDiscriminator<string>("Member_Type").HasValue("member_base");

                    b.UseTphMappingStrategy();
                });

            modelBuilder.Entity("SeniorLearnConsole.Data.MemberCourse", b =>
                {
                    b.Property<int>("memberId")
                        .HasColumnType("int");

                    b.Property<int>("CourseId")
                        .HasColumnType("int");

                    b.HasKey("memberId", "CourseId");

                    b.HasIndex("CourseId");

                    b.ToTable("MemberSession");
                });

            modelBuilder.Entity("SeniorLearnConsole.Data.Session", b =>
                {
                    b.Property<int>("sessionId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("sessionId"));

                    b.Property<int>("CourseId")
                        .HasColumnType("int");

                    b.Property<DateTime>("Date")
                        .HasColumnType("datetime2");

                    b.HasKey("sessionId");

                    b.HasIndex("CourseId");

                    b.ToTable("Sessions");
                });

            modelBuilder.Entity("SeniorLearnConsole.Data.ProMember", b =>
                {
                    b.HasBaseType("SeniorLearnConsole.Data.Member");

                    b.Property<int>("proId")
                        .HasColumnType("int");

                    b.HasDiscriminator().HasValue("member_pro");
                });

            modelBuilder.Entity("SeniorLearnConsole.Data.Course", b =>
                {
                    b.HasOne("SeniorLearnConsole.Data.ProMember", "ProMember")
                        .WithMany("CreatedCourses")
                        .HasForeignKey("ProMembermemberId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ProMember");
                });

            modelBuilder.Entity("SeniorLearnConsole.Data.MemberCourse", b =>
                {
                    b.HasOne("SeniorLearnConsole.Data.Course", "course")
                        .WithMany("MemberCourse")
                        .HasForeignKey("CourseId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SeniorLearnConsole.Data.Member", "member")
                        .WithMany("MemberCourse")
                        .HasForeignKey("memberId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("course");

                    b.Navigation("member");
                });

            modelBuilder.Entity("SeniorLearnConsole.Data.Session", b =>
                {
                    b.HasOne("SeniorLearnConsole.Data.Course", "Course")
                        .WithMany("Sessions")
                        .HasForeignKey("CourseId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Course");
                });

            modelBuilder.Entity("SeniorLearnConsole.Data.Course", b =>
                {
                    b.Navigation("MemberCourse");

                    b.Navigation("Sessions");
                });

            modelBuilder.Entity("SeniorLearnConsole.Data.Member", b =>
                {
                    b.Navigation("MemberCourse");
                });

            modelBuilder.Entity("SeniorLearnConsole.Data.ProMember", b =>
                {
                    b.Navigation("CreatedCourses");
                });
#pragma warning restore 612, 618
        }
    }
}
