// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using SeniorLearnDataSeed.Data;

#nullable disable

namespace SeniorLearnDataSeed.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20240915120214_addMBSession")]
    partial class addMBSession
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("SeniorLearnDataSeed.Data.Course", b =>
                {
                    b.Property<int>("CourseId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("CourseId"));

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("MemberId")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("isStandAlone")
                        .HasColumnType("bit");

                    b.HasKey("CourseId");

                    b.HasIndex("MemberId");

                    b.ToTable("Courses");

                    b.HasData(
                        new
                        {
                            CourseId = 1,
                            Description = "Beginner's guide to gardening",
                            MemberId = 1,
                            Name = "Gardening",
                            isStandAlone = true
                        });
                });

            modelBuilder.Entity("SeniorLearnDataSeed.Data.Enrollment", b =>
                {
                    b.Property<int>("EnrollmentId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("EnrollmentId"));

                    b.Property<int>("MemberId")
                        .HasColumnType("int");

                    b.Property<int>("SessionId")
                        .HasColumnType("int");

                    b.HasKey("EnrollmentId");

                    b.HasIndex("MemberId");

                    b.HasIndex("SessionId");

                    b.ToTable("Enrollments");

                    b.HasData(
                        new
                        {
                            EnrollmentId = 1,
                            MemberId = 2,
                            SessionId = 1
                        },
                        new
                        {
                            EnrollmentId = 2,
                            MemberId = 2,
                            SessionId = 2
                        });
                });

            modelBuilder.Entity("SeniorLearnDataSeed.Data.Member", b =>
                {
                    b.Property<int>("MemberId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("MemberId"));

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("StartDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("Type")
                        .HasColumnType("int");

                    b.HasKey("MemberId");

                    b.ToTable("Members");

                    b.HasData(
                        new
                        {
                            MemberId = 1,
                            Email = "saxon.cadet@gelos.com",
                            FirstName = "Saxon",
                            LastName = "Cadet",
                            StartDate = new DateTime(2024, 9, 15, 22, 2, 14, 70, DateTimeKind.Local).AddTicks(626),
                            Type = 0
                        },
                        new
                        {
                            MemberId = 2,
                            Email = "sean.saap@gelos.com",
                            FirstName = "Sean",
                            LastName = "Saap",
                            StartDate = new DateTime(2024, 9, 15, 22, 2, 14, 70, DateTimeKind.Local).AddTicks(664),
                            Type = 1
                        });
                });

            modelBuilder.Entity("SeniorLearnDataSeed.Data.Payment", b =>
                {
                    b.Property<int>("PaymentId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("PaymentId"));

                    b.Property<double>("AmountPaid")
                        .HasColumnType("float");

                    b.Property<int>("MemberId")
                        .HasColumnType("int");

                    b.Property<int>("PaymentType")
                        .HasColumnType("int");

                    b.HasKey("PaymentId");

                    b.HasIndex("MemberId");

                    b.ToTable("Payments");

                    b.HasData(
                        new
                        {
                            PaymentId = 1,
                            AmountPaid = 100.0,
                            MemberId = 1,
                            PaymentType = 0
                        },
                        new
                        {
                            PaymentId = 2,
                            AmountPaid = 150.0,
                            MemberId = 2,
                            PaymentType = 4
                        });
                });

            modelBuilder.Entity("SeniorLearnDataSeed.Data.Session", b =>
                {
                    b.Property<int>("SessionId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("SessionId"));

                    b.Property<int?>("CourseId")
                        .HasColumnType("int");

                    b.Property<DateTime>("Date")
                        .HasColumnType("datetime2");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<string>("session_type")
                        .IsRequired()
                        .HasMaxLength(21)
                        .HasColumnType("nvarchar(21)");

                    b.HasKey("SessionId");

                    b.HasIndex("CourseId");

                    b.ToTable("Sessions");

                    b.HasDiscriminator<string>("session_type").HasValue("session_base");

                    b.UseTphMappingStrategy();
                });

            modelBuilder.Entity("SeniorLearnDataSeed.Data.OnPremSession", b =>
                {
                    b.HasBaseType("SeniorLearnDataSeed.Data.Session");

                    b.Property<string>("StreetName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("StreetNumber")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Suburb")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasDiscriminator().HasValue("session_onprem");

                    b.HasData(
                        new
                        {
                            SessionId = 2,
                            CourseId = 2,
                            Date = new DateTime(2024, 9, 15, 22, 2, 14, 70, DateTimeKind.Local).AddTicks(845),
                            Status = 1,
                            StreetName = "Pitt Street",
                            StreetNumber = "25A",
                            Suburb = "Sydney"
                        });
                });

            modelBuilder.Entity("SeniorLearnDataSeed.Data.OnlineSession", b =>
                {
                    b.HasBaseType("SeniorLearnDataSeed.Data.Session");

                    b.Property<string>("AdditionalDetails")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("MeetingCode")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("OnlineLink")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasDiscriminator().HasValue("session_online");

                    b.HasData(
                        new
                        {
                            SessionId = 1,
                            CourseId = 1,
                            Date = new DateTime(2024, 9, 15, 22, 2, 14, 70, DateTimeKind.Local).AddTicks(826),
                            Status = 1,
                            AdditionalDetails = "Cameras are required",
                            OnlineLink = "microsoft.com"
                        });
                });

            modelBuilder.Entity("SeniorLearnDataSeed.Data.Course", b =>
                {
                    b.HasOne("SeniorLearnDataSeed.Data.Member", "Member")
                        .WithMany("CreatedCourses")
                        .HasForeignKey("MemberId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Member");
                });

            modelBuilder.Entity("SeniorLearnDataSeed.Data.Enrollment", b =>
                {
                    b.HasOne("SeniorLearnDataSeed.Data.Member", "Member")
                        .WithMany("Enrollments")
                        .HasForeignKey("MemberId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SeniorLearnDataSeed.Data.Session", "Session")
                        .WithMany("EnrolledMembers")
                        .HasForeignKey("SessionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Member");

                    b.Navigation("Session");
                });

            modelBuilder.Entity("SeniorLearnDataSeed.Data.Payment", b =>
                {
                    b.HasOne("SeniorLearnDataSeed.Data.Member", "Member")
                        .WithMany("Payments")
                        .HasForeignKey("MemberId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Member");
                });

            modelBuilder.Entity("SeniorLearnDataSeed.Data.Session", b =>
                {
                    b.HasOne("SeniorLearnDataSeed.Data.Course", "Course")
                        .WithMany("Sessions")
                        .HasForeignKey("CourseId");

                    b.Navigation("Course");
                });

            modelBuilder.Entity("SeniorLearnDataSeed.Data.Course", b =>
                {
                    b.Navigation("Sessions");
                });

            modelBuilder.Entity("SeniorLearnDataSeed.Data.Member", b =>
                {
                    b.Navigation("CreatedCourses");

                    b.Navigation("Enrollments");

                    b.Navigation("Payments");
                });

            modelBuilder.Entity("SeniorLearnDataSeed.Data.Session", b =>
                {
                    b.Navigation("EnrolledMembers");
                });
#pragma warning restore 612, 618
        }
    }
}
